# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday001',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tidytuesday001',
                'lib_path': 'tidytuesday001'},
  'syms': {'tidytuesday001.core': {'tidytuesday001.core.foo': ('core.html#foo', 'tidytuesday001/core.py')}}}
